### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tygoee**
I saw how you wanted to automatically download `requests` and `pyyaml`, so I made an implementation using the built-in venv module. Then I wanted to see if it ran, but it had some unfixed errors: passing the wrong amount of arguments to functions, some repeating code and some unfinished code. I also figured it would be nice to add typing :)

If you didn't know, you can enable [strict typing](https://code.visualstudio.com/docs/python/settings-reference#_pylance-language-server) on VSCode by going to your settings.json file and adding `"python.analysis.typeCheckingMode": "strict"`, this will help a lot of problems in the long run

This took a few hours, I hope you like it

### CODE REVIEW

**Comment by tygoee** [comment]
@RandomGgames ?

**Review by RandomGgames — COMMENTED** [review]
Just a heads up, I'm quite particular about my coding style, and it's not a reflection of your work, which I appreciate your interest in. While I see some great changes here, there are a few that don't align with my preferred style or readability. I'll need some time to review and selectively merge the changes that match my coding approach. I'll make a commit to your branch in the future, though I do not know when. It's been a while since I've wanted to work on this project and start changing things.

**Comment by RandomGgames** [comment]
I'm sick and haven't been able to sleep, but got the urge to look into this after writing my last comment. I've finished going through, cherry picking what I like and modifying/removing what I don't like. Like I said before, I appreciate the interest, I'm just particular. But wow, thank you for the work you've put into this. I've learned a lot just from going through it! I've got to get back into working on this update. There is still things I don't like that I'll eventually rework (from my old code) when I get the urge again.

Some notes about what I kept/didn't keep/why and also me just blabbing cuz I'm tired and it's late:
- Auto installation of yaml and requests: I feel as though it isn't truly necessary unless it could be done in like 2-3 lines, so I've just removed it. I just wasn't a fan of having all that code for a one time purpose for most, even if it did work. Just personal preference.
- Type hints: I have never used type hints before, nor did I know how to or even know they existed really. I like them! I'll need to learn how to use them more often.
- Changing extractNestedStrings(): I didn't know about match cases either, which are pretty cool. The function didn't need to get changed change but I like it so I've modified your changes a bit and kept them.
- Function hints for inputs and outputs: I like em! I originally didn't add them to all functions because some took non-standard inputs, though now with type hints I'm thankful you added them back.
- Long lines: Just personal preference, I don't split some long lines even if I probably should. What makes me decide which are long and which aren't? No idea, just gut feeling.

**Comment by tygoee** [comment]
Sorry for the late reply, but thanks for the feedback!

- The auto-installation is indeed not really necessary, I just thought you'd like it as you tried to implement it earlier.
- Type hints are just nice for code security. If you haven't yet enabled it, I'd recommend it via your vscode settings using `"python.analysis.typeCheckingMode": "strict"` in the settings.
- I thought a match case would be more fitting, but often it's just preference 
- Thanks, it really took a while
- I also think my formatter auto-split some long lines, it's just preference

**Pull request merged**
